run:
  tests: true
  modules-download-mode: vendor
  skip-dirs:
    - internal/proto
    - vendor
linters:
  disable-all: true
  enable:
    #- deadcode
    - errcheck
    - forbidigo
    - goconst
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - promlinter
    - revive
    - staticcheck
    #- structcheck
    - unused
    #- varcheck
    - whitespace
linters-settings:
  forbidigo:
    forbid:
      #- fmt.Print.*
      - os.Exit
  govet:
    check-shadowing: true
    enable-all: true
  revive:
    severity: warning
    confidence: 0.8
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  exclude:
    # yamllint disable-line rule:line-length
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
    - 'shadow: declaration of "err" shadows declaration at line (\d+)'
    - 'SA1019: package github.com/golang/protobuf/(.*) is deprecated:'
    - 'SA1019: grpc.CustomCodec is deprecated'
    - 'G104: Errors unhandled'
